### ISSUE TITLE
Inefficient code

### ISSUE THREAD

**Issue by golddragon007** [openeuropa/oe_media#199]
Here between 46 and 61 lines, the comment and the corresponding implementation are not true.
https://github.com/openeuropa/oe_media/blob/master/modules/oe_media_iframe/src/Plugin/Filter/FilterIframeTag.php#L46-61

There are two solutions for that:
1. Iterate backwards with the "for" loop, and then you can do it with a single loop. (optimal)
2. Create a copy of the object, iterate in one, and remove it from the other. (double memory usage)

**Comment by brummbar** [comment]
Closing because:

- reverse loop is a micro optimisation. Php loops are very fast, indicating a double loop as "inefficient" is an exaggeration.
- the statement "the comment and the corresponding implementation are not true" is false. See php documentation linked regarding directly modifying the children for the second part of the comment. The first part regarding text nodes being rendered inside iframe tags is also true.
