### ISSUE TITLE
Not possible to install 0.4.0 version

### ISSUE THREAD

**Issue by golddragon007** [openeuropa/oe_media#62]
If another module was enabled, which already created the following config files, then it's not possible to install it, just by removing the configs first (well if you don't have config and content which relies already on this).
- core.entity_form_display.media.image.default
- core.entity_view_display.media.image.default
- media.type.image 

Error message on install:
Unable to install OpenEuropa Media, core.entity_form_display.media.image.default, core.entity_view_display.media.image.default, media.type.image already exist in active configuration.

**Comment by brummbar** [comment]
This was caused by an early installation of the core media module, which brings in the media image bundle. Unfortunately, since we ship configurations with same name, it's needed to either:

- enable oe_media instead of media;
- if media is already enabled, delete the conflicting configurations frome the config/install folder of oe_media before enabling it.
